FILES = conclusion.tex improvements.tex presentation.tex report.tex implementation.tex introduction.tex problems.tex report.tex


report: $(FILES)
	pdflatex -shell-escape report.tex
	xdg-open report.pdf
