#ifndef BUFFERATTRIBUTE_H
#define BUFFERATTRIBUTE_H

enum BufferAttribute {
    VERTEX_BUFFER,
    COLOUR_BUFFER,
    NORMAL_BUFFER,
    INDEX_BUFFER,
    TEXTURE_BUFFER,
    DELAY_BUFFER,
    VELOCITY_BUFFER,
    OFFSET_BUFFER,
    LIFETIME_BUFFER,
    BUFFER_COUNT,
};

#endif // BUFFERATTRIBUTE_H
